# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_page', models.CharField(default='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0438 \u043e\u0431\u0449\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f', max_length=50)),
                ('phone_country', models.CharField(default='+7', max_length=3)),
                ('phone_code', models.CharField(default='925', max_length=5)),
                ('phone_number', models.CharField(default='346-07-27', max_length=10)),
                ('email', models.CharField(default='fond-schastie@hotmail.com', max_length=30)),
                ('youtube', models.CharField(default='https://www.youtube.com/channel/UC20_z5bq_QyONSbVNtb3EVg', max_length=100)),
                ('fb', models.CharField(default='https://www.facebook.com/fond.schastie/', max_length=100)),
                ('insta', models.CharField(default='https://www.instagram.com/fond_schastie/', max_length=100)),
                ('words', models.CharField(default=' ', max_length=1000)),
                ('title', models.CharField(default=' ', max_length=100)),
                ('name', models.CharField(default='\u0414\u0438\u0430\u043d\u0430 \u041c\u0435\u043d\u0438\u043d\u0431\u0430\u0435\u0432\u0430', max_length=100)),
                ('photo', models.FileField(default='', upload_to='CEO')),
            ],
        ),
    ]
