# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('img', models.FileField(upload_to='slider')),
                ('link', models.CharField(default='https://www.instagram.com/fond_schastie/', max_length=100)),
                ('name', models.CharField(default='\u0421\u043b\u0430\u0439\u0434\u0435\u0440 \u2116', max_length=50)),
            ],
        ),
    ]
