# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='photo',
            field=models.FileField(default='', upload_to='media/CEO'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='words',
            field=tinymce.models.HTMLField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.FileField(upload_to='media/slider'),
        ),
    ]
