# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0003_auto_20170511_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041f\u0430\u0440\u0442\u043d\u0435\u0440 \u2116', max_length=50)),
                ('link', models.CharField(default='https://www.instagram.com/fond_schastie/', max_length=100)),
                ('img', models.FileField(upload_to='media/parner')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
