# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 08:06
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='ps',
            field=tinymce.models.HTMLField(default=' ', max_length=1000),
        ),
    ]
