# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0006_wwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0421\u0447\u0430\u0441\u0442\u044c\u0435 is - ', max_length=50)),
                ('img', models.FileField(upload_to='media/videos_cover')),
                ('link', models.CharField(default='https://www.youtube.com/channel/UC20_z5bq_QyONSbVNtb3EVg', max_length=150)),
            ],
        ),
    ]
