# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0008_auto_20170515_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='How_to_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0411\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0430\u043a\u0446\u0438\u044f \u0411\u0430\u043d\u0430\u043d', max_length=200)),
                ('img', models.FileField(blank=True, upload_to='media/how_to_help')),
                ('text', tinymce.models.HTMLField(default='\u0417\u0430\u0434\u0430\u0447\u0435\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c \u044f\u0432\u043b\u0435\u044f\u0435\u0442\u0441\u044f \u0446\u0435\u043b\u0435\u0432\u044b\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0438 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u044f', max_length=2000)),
            ],
        ),
    ]
