# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0009_how_to_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('name', models.CharField(default='\u0411\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0430\u043a\u0446\u0438\u044f \u0411\u0430\u043d\u0430\u043d', max_length=200)),
                ('short_text', tinymce.models.HTMLField(default='\u0417\u0430\u0434\u0430\u0447\u0435\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c \u044f\u0432\u043b\u0435\u044f\u0435\u0442\u0441\u044f \u0446\u0435\u043b\u0435\u0432\u044b\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0438 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u044f...', max_length=2000)),
                ('full_text', tinymce.models.HTMLField(default='\u0417\u0430\u0434\u0430\u0447\u0435\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c \u044f\u0432\u043b\u0435\u044f\u0435\u0442\u0441\u044f \u0446\u0435\u043b\u0435\u0432\u044b\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0438 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u044f...', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Media_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_media', models.ImageField(default='', upload_to='images')),
                ('small_image', models.ImageField(default='', upload_to='images')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webhappy.Media')),
            ],
        ),
    ]
