# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0010_media_media_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='cover',
            field=models.ImageField(default='', upload_to='cover'),
        ),
    ]
