# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0011_media_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='small_cover',
            field=models.ImageField(blank=True, default='', upload_to='cover'),
        ),
    ]
