# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0012_media_small_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='small_cover',
            field=models.ImageField(blank=True, default='', editable=False, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='media_images',
            name='small_image',
            field=models.ImageField(default='', editable=False, upload_to='images'),
        ),
    ]
