# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0013_auto_20170804_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='adress',
            field=models.CharField(default='\u0410\u0434\u0440\u0435\u0441: \u0433. \u041c\u043e\u0441\u043a\u0432\u0430, \u0443\u043b. \u0422\u0432\u0435\u0440\u0441\u043a\u0430\u044f, 23', max_length=150),
        ),
    ]
