# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhappy', '0015_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '\u041e \u0424\u043e\u043d\u0434\u0435', 'verbose_name_plural': '\u041e \u0424\u043e\u043d\u0434\u0435'},
        ),
        migrations.AlterModelOptions(
            name='how_to_help',
            options={'verbose_name': '\u041a\u0430\u043a \u043f\u043e\u043c\u043e\u0447\u044c', 'verbose_name_plural': '\u041a\u0430\u043a \u043f\u043e\u043c\u043e\u0447\u044c'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '\u0424\u043e\u0442\u043e\u0430\u043b\u044c\u0431\u043e\u043c - \u0447\u0442\u043e \u043c\u044b \u0434\u0435\u043b\u0430\u0435\u043c', 'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0430\u043b\u044c\u0431\u043e\u043c\u044b - \u0447\u0442\u043e \u043c\u044b \u0434\u0435\u043b\u0430\u0435\u043c'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '\u041f\u0430\u0440\u043d\u0442\u043d\u0435\u0440', 'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u0412\u0438\u0434\u0435\u043e', 'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e'},
        ),
        migrations.AlterModelOptions(
            name='wwd',
            options={'verbose_name': '\u0427\u0442\u043e \u043c\u044b \u0434\u0435\u043b\u0430\u0435\u043c \u0434\u043b\u044f \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b', 'verbose_name_plural': '\u0427\u0442\u043e \u043c\u044b \u0434\u0435\u043b\u0430\u0435\u043c \u0434\u043b\u044f \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
    ]
